# Análisis de datos con Python

En esta clase veremos la herramienta de análisis de datos `pandas`. Esta herramienta es una librería que permite hacer análisis y limpieza de datos en Python. Está diseñada para trabajar con datos tabulares y heterogéneos. También es utilizada en conjunto con otras herramientas para hacer _Data Science_ como `NumPy`, `SciPy`, `matplotlib` y `scikit-learn`. El objetivo de esta clase/tutorial es tener nociones básicas de la librería `pandas` y conocer cómo esta puede hacer uso de un motor SQL.

### Outline

En esta clase vamos a ver:

- Tópicos básicos de la librería `Pandas`:
 - El tipo `Series`
 - El tipo `DataFrame`
 - Proyecciones y filtros en un `DataFrame`
 - Resumen de los datos
 - Manejar nulos
 - Agregación
 - Índices jerárquicos
 - Hacer *merge* de dos `DataFrame`
- Visualización rápida con `matplotlib`

Para comenzar con `pandas` estudiaremos los tipos `Series` y `DataFrame`. Partimos importando la librería:

In [1]:
import pandas as pd

### Series

Vamos a partir instanciando objetos de tipo `Series`. Estos objetos son como arreglos unidimensionales.

In [2]:
obj = pd.Series([1, 3, -4, 7])
obj

0    1
1    3
2   -4
3    7
dtype: int64

Index(['d', 'c', 'b', 'a'], dtype='object')

Para un objeto de tipo `Series` podemos agregar un label a sus índices.

In [3]:
obj = pd.Series([1, 3, -4, 7], index=['d', 'c', 'b', 'a'])
obj

d    1
c    3
b   -4
a    7
dtype: int64

In [61]:
obj.index

Index(['d', 'c', 'b', 'a'], dtype='object')

In [4]:
obj['c']

3

Podemos seleccionar varios elementos según el label de su índice.

In [5]:
obj[['c', 'a']]

c    3
a    7
dtype: int64

In [6]:
obj[[0, 2]]

<ipython-input-6-71be00516c30>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[0, 2]]

d    1
b   -4
dtype: int64

Podemos hacer filtros pasando un arreglo de _booleanos_:

In [7]:
obj[obj > 2]

c    3
a    7
dtype: int64

Recordemos lo que significaba la comparación `obj > 2` en `NumPy`. Esta comparación era una arreglo con el mismo largo que `obj` que tenía el valor `True` en todas las posiciones con valor mayor a 2.

Por lo que en `obj[obj > 2]` se muestran sólo las filas en la que el arreglo anterior era `True`.

Finalmente, podemos crear un objeto `Series` a partir de un diccionario. Supongamos el siguiente diccionario de personas junto a su edad.

In [8]:
obj > 2

d    False
c     True
b    False
a     True
dtype: bool

In [9]:
obj[obj > 2]

c    3
a    7
dtype: int64

In [10]:
people = {'Alice': 20, 'Bob': 17, 'Charles': 23, 'Dino': None}
people_series = pd.Series(people)
people_series

Alice      20.0
Bob        17.0
Charles    23.0
Dino        NaN
dtype: float64

¿Qué pasa si queremos filtrar por ciertos nombres pero algunos no existen? **Spoiler**: tendremos un error.

In [11]:
people_series[['Bob', 'Dino', 'Edward']]

KeyError: "['Edward'] not in index"

### DataFrame

Un objeto de tipo `DataFrame` representa una tabla, en que cada una de sus columnas representa un tipo. Vamos a construir una tabla a partir de un diccionario.

In [12]:
reg_chile = {'name': ['Metropolitana', 'Valparaiso', 'Biobío', 'Maule', 'Araucanía', 'O\'Higgins'],
             'pop': [7112808, 1815902, 1538194, 1044950, 957224, 914555],
             'pib': [24850, 14510, 13281, 12695, 11064, 14840]}
frame = pd.DataFrame(reg_chile)
frame

            name      pop    pib
0  Metropolitana  7112808  24850
1     Valparaiso  1815902  14510
2         Biobío  1538194  13281
3          Maule  1044950  12695
4      Araucanía   957224  11064
5      O'Higgins   914555  14840

Podemos usar la función `head` para tener sólo las 5 primeras columnas del Data Frame. En este caso no es mucho aporte, pero para un Data Frame más grande no puede servir para ver cómo vienen los datos.

In [13]:
frame.head()

            name      pop    pib
0  Metropolitana  7112808  24850
1     Valparaiso  1815902  14510
2         Biobío  1538194  13281
3          Maule  1044950  12695
4      Araucanía   957224  11064

Podemos proyectar valores pasando el nombre de las columnas que deseamos dejar.

In [14]:
frame[['name']]

            name
0  Metropolitana
1     Valparaiso
2         Biobío
3          Maule
4      Araucanía
5      O'Higgins

In [15]:
frame[['name', 'pop']]

            name      pop
0  Metropolitana  7112808
1     Valparaiso  1815902
2         Biobío  1538194
3          Maule  1044950
4      Araucanía   957224
5      O'Higgins   914555

Podemos seleccionar una determinada fila con la función `iloc`.

In [16]:
frame.iloc[2]

name     Biobío
pop     1538194
pib       13281
Name: 2, dtype: object

Podemos utilizar la misma idea de filtros vista anteriormente. Por ejemplo, vamos a dejar sólamente las columnas con población mayor a 1.000.000.

In [17]:
frame['pop'] > 1000000

0     True
1     True
2     True
3     True
4    False
5    False
Name: pop, dtype: bool

In [18]:
frame[frame['pop'] > 1000000]

            name      pop    pib
0  Metropolitana  7112808  24850
1     Valparaiso  1815902  14510
2         Biobío  1538194  13281
3          Maule  1044950  12695

Podemos hacer filtros con `&` para hacer un `AND`:

In [19]:
frame[(frame['pop'] > 1000000) & (frame['pib'] < 20000)]

         name      pop    pib
1  Valparaiso  1815902  14510
2      Biobío  1538194  13281
3       Maule  1044950  12695

Y podemos usar `|` para hacer un `OR`:

In [20]:
frame[(frame['name'] == 'Metropolitana') | (frame['name'] == 'Valparaiso')]

            name      pop    pib
0  Metropolitana  7112808  24850
1     Valparaiso  1815902  14510

Existen muchas formas de crear y operar sobre un `DataFrame`. Puedes revisar la documentación para encontrar más.

### Orden sobre un Data Frame

Para ordenar un objeto `DataFrame` usamos la función `sort_values` (con ascending le indicamos orden ascendente o descendente):

In [21]:
frame.sort_values(by='name', ascending=True)

            name      pop    pib
4      Araucanía   957224  11064
2         Biobío  1538194  13281
3          Maule  1044950  12695
0  Metropolitana  7112808  24850
5      O'Higgins   914555  14840
1     Valparaiso  1815902  14510

Si necesitamos ordenar por más de una columna, podemos pasar un arreglo al argumento `by`.

### Describiendo los datos

La librería `pandas` tiene varias funciones que nos permiten obtener descripciones y resúmenes de los datos. Vamos a ver algunos ejemplos.

In [22]:
frame.describe()

                pop           pib
count  6.000000e+00      6.000000
mean   2.230606e+06  15206.666667
std    2.418536e+06   4915.119843
min    9.145550e+05  11064.000000
25%    9.791555e+05  12841.500000
50%    1.291572e+06  13895.500000
75%    1.746475e+06  14757.500000
max    7.112808e+06  24850.000000

In [23]:
frame['pop'].mean()

2230605.5

In [24]:
frame.sum()

name    MetropolitanaValparaisoBiobíoMauleAraucaníaO'H...
pop                                              13383633
pib                                                 91240
dtype: object

## Importar archivos csv

Ahora vamos a importar el archivo pero como csv con la función `read_csv`.

In [38]:
com_frame = pd.read_csv("comunas.csv", header=None)

In [39]:
com_frame.head()

,0,1,2,3,4,5,6,7
0,15101,Arica,Arica,Arica y Parinacota,4799.4,210936,736.0,38.40
1,15102,Camarones,Arica,Arica y Parinacota,3927.0,679,0.3,751.00
2,15201,Putre,Parinacota,Arica y Parinacota,5902.5,1462,0.2,707.00
3,15202,General Lagos,Parinacota,Arica y Parinacota,2244.4,739,0.5,0.67
4,1101,Iquique,Iquique,Tarapacá,2242.1,184953,82.4,766.00

Notamos que no hay un encabezado para los datos, lo vamos a agregar a mano.

In [40]:
com_frame.columns = ['cod', 'nombre', 'prov', 'reg', 'sup', 'pobl', 'dens', 'idh']
com_frame

,cod,nombre,prov,reg,sup,pobl,dens,idh
0,15101,Arica,Arica,Arica y Parinacota,4799.4,210936,736.0,38.40
1,15102,Camarones,Arica,Arica y Parinacota,3927.0,679,0.3,751.00
2,15201,Putre,Parinacota,Arica y Parinacota,5902.5,1462,0.2,707.00
3,15202,General Lagos,Parinacota,Arica y Parinacota,2244.4,739,0.5,0.67
4,1101,Iquique,Iquique,Tarapacá,2242.1,184953,82.4,766.00
...,...,...,...,...,...,...,...,...
341,13601,Talagante,Talagante,Metropolitana de Santiago,126.0,78887,474.6,749.00
342,13602,El Monte,Talagante,Metropolitana de Santiago,118.0,32468,224.2,688.00
343,13603,Isla de Maipo,Talagante,Metropolitana de Santiago,189.0,33723,136.5,724.00
344,13604,Padre Hurtado,Talagante,Metropolitana de Santiago,80.8,50696,626.2,728.00
345,13605,Peñaflor,Talagante,Metropolitana de Santiago,69.0,87741,965.5,753.00

In [41]:
com_frame.describe()

                cod           sup           pobl          dens         idh
count    346.000000  3.460000e+02     346.000000    346.000000  341.000000
mean    8563.156069  5.815967e+03   50407.078035    884.646821  637.527654
std     3356.540795  6.727407e+04   86926.943488   2668.330303  188.322684
min     1101.000000  7.000000e+00     127.000000      0.000000    0.510000
25%     6109.250000  2.513000e+02    9148.500000      9.325000  637.000000
50%     8313.500000  6.331500e+02   17688.000000     26.100000  672.000000
75%    11176.250000  1.657500e+03   50747.000000     89.575000  719.000000
max    15202.000000  1.250258e+06  805000.000000  15667.000000  949.000000

En esta tabla tenemos valores nulos. Vamos a buscarlos. Primero vamos a encontrar todas las filas que contengan algún nulo, para luego filtrar por ese arreglo.

In [42]:
com_frame.isnull().any(axis=1) #1 ve por fila, 0 (default) ve por columnas, None ve por todo

0      False
1      False
2      False
3      False
4      False
       ...
341    False
342    False
343    False
344    False
345    False
Length: 346, dtype: bool

In [43]:
com_frame[com_frame.isnull().any(axis=1)]

,cod,nombre,prov,reg,sup,pobl,dens,idh
5,1107,Alto Hospicio,Iquique,Tarapacá,572.9,94455,87.6,NaN
177,8112,Hualpén,Concepción,Biobío,53.5,86176,1610.8,NaN
198,8314,Alto Biobío,Biobío,Biobío,2124.6,10039,4.7,NaN
219,9121,Cholchol,Cautín,La Araucanía,427.9,10825,25.3,NaN
288,12202,Antártica,Antártica Chilena,Magallanes y Antártica Chilena,1250257.6,127,0.0,NaN

In [44]:
com_frame.iloc[[5,177,198,219,288 ], :]

,cod,nombre,prov,reg,sup,pobl,dens,idh
5,1107,Alto Hospicio,Iquique,Tarapacá,572.9,94455,87.6,NaN
177,8112,Hualpén,Concepción,Biobío,53.5,86176,1610.8,NaN
198,8314,Alto Biobío,Biobío,Biobío,2124.6,10039,4.7,NaN
219,9121,Cholchol,Cautín,La Araucanía,427.9,10825,25.3,NaN
288,12202,Antártica,Antártica Chilena,Magallanes y Antártica Chilena,1250257.6,127,0.0,NaN

`pandas` tiene métodos auxiliares para lidiar con datos faltantes. Uno es eliminar aquellas filas con la función `dropna()`

In [45]:
com_cleaned = com_frame.dropna()
com_cleaned

,cod,nombre,prov,reg,sup,pobl,dens,idh
0,15101,Arica,Arica,Arica y Parinacota,4799.4,210936,736.0,38.40
1,15102,Camarones,Arica,Arica y Parinacota,3927.0,679,0.3,751.00
2,15201,Putre,Parinacota,Arica y Parinacota,5902.5,1462,0.2,707.00
3,15202,General Lagos,Parinacota,Arica y Parinacota,2244.4,739,0.5,0.67
4,1101,Iquique,Iquique,Tarapacá,2242.1,184953,82.4,766.00
...,...,...,...,...,...,...,...,...
341,13601,Talagante,Talagante,Metropolitana de Santiago,126.0,78887,474.6,749.00
342,13602,El Monte,Talagante,Metropolitana de Santiago,118.0,32468,224.2,688.00
343,13603,Isla de Maipo,Talagante,Metropolitana de Santiago,189.0,33723,136.5,724.00
344,13604,Padre Hurtado,Talagante,Metropolitana de Santiago,80.8,50696,626.2,728.00
345,13605,Peñaflor,Talagante,Metropolitana de Santiago,69.0,87741,965.5,753.00

In [46]:
com_cleaned.iloc[[5,177,198,219,288 ], :]

,cod,nombre,prov,reg,sup,pobl,dens,idh
6,1401,Pozo Almonte,Tamarugal,Tarapacá,13765.8,11519,0.7,722.00
179,8202,Arauco,Arauco,Biobío,956.1,41153,43.0,704.00
201,9103,Cunco,Cautín,La Araucanía,1906.5,19024,10.0,659.00
223,9204,Ercilla,Malleco,La Araucanía,499.7,9148,18.3,609.00
293,12402,Torres del Paine,Última Esperanza,Magallanes y Antártica Chilena,6630.0,1163,0.1,0.73

Verifiquemos si la limpió

In [47]:
com_cleaned[com_cleaned.isnull().any(axis=1)]

Empty DataFrame
Columns: [cod, nombre, prov, reg, sup, pobl, dens, idh]
Index: []

O podemos tomar una opción menos radical, que es reemplazar los nulos por un valor en particular.

In [48]:
com_frame = com_frame.fillna(0)
com_frame

,cod,nombre,prov,reg,sup,pobl,dens,idh
0,15101,Arica,Arica,Arica y Parinacota,4799.4,210936,736.0,38.40
1,15102,Camarones,Arica,Arica y Parinacota,3927.0,679,0.3,751.00
2,15201,Putre,Parinacota,Arica y Parinacota,5902.5,1462,0.2,707.00
3,15202,General Lagos,Parinacota,Arica y Parinacota,2244.4,739,0.5,0.67
4,1101,Iquique,Iquique,Tarapacá,2242.1,184953,82.4,766.00
...,...,...,...,...,...,...,...,...
341,13601,Talagante,Talagante,Metropolitana de Santiago,126.0,78887,474.6,749.00
342,13602,El Monte,Talagante,Metropolitana de Santiago,118.0,32468,224.2,688.00
343,13603,Isla de Maipo,Talagante,Metropolitana de Santiago,189.0,33723,136.5,724.00
344,13604,Padre Hurtado,Talagante,Metropolitana de Santiago,80.8,50696,626.2,728.00
345,13605,Peñaflor,Talagante,Metropolitana de Santiago,69.0,87741,965.5,753.00

Verifiquemos si puso el 0

In [50]:
com_frame.iloc[[5,177,198,219,288]]

,cod,nombre,prov,reg,sup,pobl,dens,idh
5,1107,Alto Hospicio,Iquique,Tarapacá,572.9,94455,87.6,0.0
177,8112,Hualpén,Concepción,Biobío,53.5,86176,1610.8,0.0
198,8314,Alto Biobío,Biobío,Biobío,2124.6,10039,4.7,0.0
219,9121,Cholchol,Cautín,La Araucanía,427.9,10825,25.3,0.0
288,12202,Antártica,Antártica Chilena,Magallanes y Antártica Chilena,1250257.6,127,0.0,0.0

Existen muchas otras opciones para limpiar los datos, pero no los veremos en este tutorial.

### Agregación

Vamos a ver unos ejemplos para agregar datos utilizando `pandas`. Vamos a calcular la cantidad de habitantes por región.

In [51]:
com_frame['pobl'].groupby(com_frame['reg']).sum() # Ojo! esto retorna un objeto Series

reg
Antofagasta                             551627
Arica y Parinacota                      213816
Atacama                                 292054
Aysén del Gral. C. Ibáñez del Campo     106893
Biobío                                 1565839
Coquimbo                                714856
La Araucanía                            933537
Lib. Gral. Bernardo O'Higgins           903248
Los Lagos                               835829
Los Ríos                                380618
Magallanes y Antártica Chilena          158828
Maule                                  1073635
Metropolitana de Santiago              7090580
Tarapacá                                300021
Valparaíso                             1859312
Ñuble                                   460156
Name: pobl, dtype: int64

Podemos preguntar cuantos elementos hay por grupo. En este caso obtendríamos el número de comunas por región.

In [52]:
com_frame['nombre'].groupby(com_frame['reg']).size() # Ojo! esto retorna un objeto Series

reg
Antofagasta                             9
Arica y Parinacota                      4
Atacama                                 9
Aysén del Gral. C. Ibáñez del Campo    10
Biobío                                 33
Coquimbo                               15
La Araucanía                           32
Lib. Gral. Bernardo O'Higgins          33
Los Lagos                              30
Los Ríos                               12
Magallanes y Antártica Chilena         11
Maule                                  30
Metropolitana de Santiago              52
Tarapacá                                7
Valparaíso                             38
Ñuble                                  21
Name: nombre, dtype: int64

In [53]:
com_frame['nombre'].groupby(com_frame['reg']).count() # Ojo! esto retorna un objeto Series

reg
Antofagasta                             9
Arica y Parinacota                      4
Atacama                                 9
Aysén del Gral. C. Ibáñez del Campo    10
Biobío                                 33
Coquimbo                               15
La Araucanía                           32
Lib. Gral. Bernardo O'Higgins          33
Los Lagos                              30
Los Ríos                               12
Magallanes y Antártica Chilena         11
Maule                                  30
Metropolitana de Santiago              52
Tarapacá                                7
Valparaíso                             38
Ñuble                                  21
Name: nombre, dtype: int64

In [54]:
a=com_frame['pobl'].groupby([com_frame['prov'], com_frame['reg']]).sum() # Ojo! esto retorna un objeto Series

In [ ]:
a.keys()

MultiIndex([(            'Antofagasta',                         'Antofagasta'),
            (      'Antártica Chilena',      'Magallanes y Antártica Chilena'),
            (                 'Arauco',                              'Biobío'),
            (                  'Arica',                  'Arica y Parinacota'),
            (                  'Aysén', 'Aysén del Gral. C. Ibáñez del Campo'),
            (                 'Biobío',                              'Biobío'),
            (              'Cachapoal',       'Lib. Gral. Bernardo O'Higgins'),
            (           'Capitán Prat', 'Aysén del Gral. C. Ibáñez del Campo'),
            (          'Cardenal Caro',       'Lib. Gral. Bernardo O'Higgins'),
            (              'Cauquenes',                               'Maule'),
            (                 'Cautín',                        'La Araucanía'),
            (              'Chacabuco',           'Metropolitana de Santiago'),
            (               'Chañaral',                             'Atacama'),
            (                 'Chiloé',                           'Los Lagos'),
            (                 'Choapa',                            'Coquimbo'),
            (              'Colchagua',       'Lib. Gral. Bernardo O'Higgins'),
            (             'Concepción',                              'Biobío'),
            (                'Copiapó',                             'Atacama'),
            (             'Cordillera',           'Metropolitana de Santiago'),
            (              'Coyhaique', 'Aysén del Gral. C. Ibáñez del Campo'),
            (                 'Curicó',                               'Maule'),
            (              'Diguillín',                               'Ñuble'),
            (                 'El Loa',                         'Antofagasta'),
            (                  'Elqui',                            'Coquimbo'),
            (        'General Carrera', 'Aysén del Gral. C. Ibáñez del Campo'),
            (                 'Huasco',                             'Atacama'),
            (                'Iquique',                            'Tarapacá'),
            (         'Isla de Pascua',                          'Valparaíso'),
            (                  'Itata',                               'Ñuble'),
            (                 'Limarí',                            'Coquimbo'),
            (                'Linares',                               'Maule'),
            (             'Llanquihue',                           'Los Lagos'),
            (              'Los Andes',                          'Valparaíso'),
            (             'Magallanes',      'Magallanes y Antártica Chilena'),
            (                  'Maipo',           'Metropolitana de Santiago'),
            (                'Malleco',                        'La Araucanía'),
            (            'Marga Marga',                          'Valparaíso'),
            (              'Melipilla',           'Metropolitana de Santiago'),
            (                 'Osorno',                           'Los Lagos'),
            (                 'Palena',                           'Los Lagos'),
            (             'Parinacota',                  'Arica y Parinacota'),
            (                'Petorca',                          'Valparaíso'),
            (                'Punilla',                               'Ñuble'),
            (               'Quillota',                          'Valparaíso'),
            (                  'Ranco',                            'Los Ríos'),
            (            'San Antonio',                          'Valparaíso'),
            ('San Felipe de Aconcagua',                          'Valparaíso'),
            (               'Santiago',           'Metropolitana de Santiago'),
            (              'Talagante',           'Metropolitana de Santiago'),
            (                  'Talca',                               'Maule'),
            (              'Tamarugal',                            'Tarapacá'),
            (       'Tierra del Fuego',      'Magallanes y Antártica Chilena'),
            (              'Tocopilla',                         'Antofagasta'),
            (               'Valdivia',                            'Los Ríos'),
            (             'Valparaíso',                          'Valparaíso'),
            (       'Última Esperanza',      'Magallanes y Antártica Chilena')],
           names=['prov', 'reg'])

In [62]:
a.index

MultiIndex([(            'Antofagasta',                         'Antofagasta'),
            (      'Antártica Chilena',      'Magallanes y Antártica Chilena'),
            (                 'Arauco',                              'Biobío'),
            (                  'Arica',                  'Arica y Parinacota'),
            (                  'Aysén', 'Aysén del Gral. C. Ibáñez del Campo'),
            (                 'Biobío',                              'Biobío'),
            (              'Cachapoal',       'Lib. Gral. Bernardo O'Higgins'),
            (           'Capitán Prat', 'Aysén del Gral. C. Ibáñez del Campo'),
            (          'Cardenal Caro',       'Lib. Gral. Bernardo O'Higgins'),
            (              'Cauquenes',                               'Maule'),
            (                 'Cautín',                        'La Araucanía'),
            (              'Chacabuco',           'Metropolitana de Santiago'),
            (               'Chañaral',                             'Atacama'),
            (                 'Chiloé',                           'Los Lagos'),
            (                 'Choapa',                            'Coquimbo'),
            (              'Colchagua',       'Lib. Gral. Bernardo O'Higgins'),
            (             'Concepción',                              'Biobío'),
            (                'Copiapó',                             'Atacama'),
            (             'Cordillera',           'Metropolitana de Santiago'),
            (              'Coyhaique', 'Aysén del Gral. C. Ibáñez del Campo'),
            (                 'Curicó',                               'Maule'),
            (              'Diguillín',                               'Ñuble'),
            (                 'El Loa',                         'Antofagasta'),
            (                  'Elqui',                            'Coquimbo'),
            (        'General Carrera', 'Aysén del Gral. C. Ibáñez del Campo'),
            (                 'Huasco',                             'Atacama'),
            (                'Iquique',                            'Tarapacá'),
            (         'Isla de Pascua',                          'Valparaíso'),
            (                  'Itata',                               'Ñuble'),
            (                 'Limarí',                            'Coquimbo'),
            (                'Linares',                               'Maule'),
            (             'Llanquihue',                           'Los Lagos'),
            (              'Los Andes',                          'Valparaíso'),
            (             'Magallanes',      'Magallanes y Antártica Chilena'),
            (                  'Maipo',           'Metropolitana de Santiago'),
            (                'Malleco',                        'La Araucanía'),
            (            'Marga Marga',                          'Valparaíso'),
            (              'Melipilla',           'Metropolitana de Santiago'),
            (                 'Osorno',                           'Los Lagos'),
            (                 'Palena',                           'Los Lagos'),
            (             'Parinacota',                  'Arica y Parinacota'),
            (                'Petorca',                          'Valparaíso'),
            (                'Punilla',                               'Ñuble'),
            (               'Quillota',                          'Valparaíso'),
            (                  'Ranco',                            'Los Ríos'),
            (            'San Antonio',                          'Valparaíso'),
            ('San Felipe de Aconcagua',                          'Valparaíso'),
            (               'Santiago',           'Metropolitana de Santiago'),
            (              'Talagante',           'Metropolitana de Santiago'),
            (                  'Talca',                               'Maule'),
            (              'Tamarugal',                            'Tarapacá'),
            (       'Tierra del Fuego',      'Magallanes y Antártica Chilena'),
            (              'Tocopilla',                         'Antofagasta'),
            (               'Valdivia',                            'Los Ríos'),
            (             'Valparaíso',                          'Valparaíso'),
            (       'Última Esperanza',      'Magallanes y Antártica Chilena')],
           names=['prov', 'reg'])

In [63]:
a.values

array([ 373120,    1804,  171103,  211615,   35215,  390088,  635012,
          3990,   44337,   56452,  735209,  209166,   30598,  184409,
         83934,  223899, 1004648,  188323,  792908,   60146,  309501,
        307688,  153823,  459444,    7542,   73133,  279408,    5761,
         52802,  171478,  287271,  406384,  147444,  127208,  386427,
        198328,  359795,  161346,  225987,   19049,    2201,   82061,
         99666,  206873,   95078,  155093,  149145, 5257218,  283515,
        420411,   20613,    7326,   24684,  285540,  753140,   22490])

In [59]:
a

prov                     reg
Antofagasta              Antofagasta                             373120
Antártica Chilena        Magallanes y Antártica Chilena            1804
Arauco                   Biobío                                  171103
Arica                    Arica y Parinacota                      211615
Aysén                    Aysén del Gral. C. Ibáñez del Campo      35215
Biobío                   Biobío                                  390088
Cachapoal                Lib. Gral. Bernardo O'Higgins           635012
Capitán Prat             Aysén del Gral. C. Ibáñez del Campo       3990
Cardenal Caro            Lib. Gral. Bernardo O'Higgins            44337
Cauquenes                Maule                                    56452
Cautín                   La Araucanía                            735209
Chacabuco                Metropolitana de Santiago               209166
Chañaral                 Atacama                                  30598
Chiloé                   Los Lagos                               184409
Choapa                   Coquimbo                                 83934
Colchagua                Lib. Gral. Bernardo O'Higgins           223899
Concepción               Biobío                                 1004648
Copiapó                  Atacama                                 188323
Cordillera               Metropolitana de Santiago               792908
Coyhaique                Aysén del Gral. C. Ibáñez del Campo      60146
Curicó                   Maule                                   309501
Diguillín                Ñuble                                   307688
El Loa                   Antofagasta                             153823
Elqui                    Coquimbo                                459444
General Carrera          Aysén del Gral. C. Ibáñez del Campo       7542
Huasco                   Atacama                                  73133
Iquique                  Tarapacá                                279408
Isla de Pascua           Valparaíso                                5761
Itata                    Ñuble                                    52802
Limarí                   Coquimbo                                171478
Linares                  Maule                                   287271
Llanquihue               Los Lagos                               406384
Los Andes                Valparaíso                              147444
Magallanes               Magallanes y Antártica Chilena          127208
Maipo                    Metropolitana de Santiago               386427
Malleco                  La Araucanía                            198328
Marga Marga              Valparaíso                              359795
Melipilla                Metropolitana de Santiago               161346
Osorno                   Los Lagos                               225987
Palena                   Los Lagos                                19049
Parinacota               Arica y Parinacota                        2201
Petorca                  Valparaíso                               82061
Punilla                  Ñuble                                    99666
Quillota                 Valparaíso                              206873
Ranco                    Los Ríos                                 95078
San Antonio              Valparaíso                              155093
San Felipe de Aconcagua  Valparaíso                              149145
Santiago                 Metropolitana de Santiago              5257218
Talagante                Metropolitana de Santiago               283515
Talca                    Maule                                   420411
Tamarugal                Tarapacá                                 20613
Tierra del Fuego         Magallanes y Antártica Chilena            7326
Tocopilla                Antofagasta                              24684
Valdivia                 Los Ríos                                285540
Valparaíso               Valparaíso                              753140
Última Esperanza         Magallanes y Antártica Chilena           22490
Name: pobl, dtype: int64

En `pandas` se pueden hacer operaciones mucho más complejas, pero no veremos nada avanzado en esta ocasión. Puedes revisar la documentación para ver que más puedes hacer.